###
### mapletree.moe - system configuration management
### ansible group variables
###
---
#
# convert2rhel variables
#
# yamllint disable-line rule:line-length
convert2rhel_repofile_url: "https://cdn-public.redhat.com/content/public/repofiles/convert2rhel-for-rhel-9-x86_64.repo"
convert_gpg_key_remove: true
convert_convert2rhel_repo_remove: true
convert_convert2rhel_package_remove: true
convert_reboot_requested: true
rhsm_activation_key:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/rhsm_activation_key') | string | trim }}"
rhsm_org:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/rhsm_org') | string | trim }}"

#
# rhc variables
#
rhc_auth:
  activation_keys:
    keys: [" {{ rhsm_activation_key }} "]
rhc_organization: "{{ rhsm_org }}"

#
# create_users variables
#
create_users_root_password:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/create_users_root_password') | string | trim }}"
create_users_admin_password:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/create_users_admin_password') | string | trim }}"
create_users_containers_password:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/create_users_containers_password') | string | trim }}"
create_users_admin_authorized_keys:
  # yamllint disable-line rule:line-length
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYfs1EndYHRh5WcW+jkuD7IKSvZZHM+OTqDX0RuYlY5 yuki@murasame"

#
# postfix_relay variables
#
postfix_relay_root_email:
  # "root:    admin@example.com"
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/postfix_relay_root_email') | string | trim }}"
postfix_relay_sasl_passwd:
  # yamllint disable-line rule:line-length
  "{{ lookup('ansible.builtin.unvault', 'group_vars/vault/postfix_relay_sasl_passwd') | string | trim }}"

#
# overrides for CIS hardening role
#
rhel9cis_set_boot_pass: false  # FIXME: we should do this
rhel9cis_ipv6_required: false  # FIXME: we should do this too
rhel9cis_config_aide: false  # TODO: maybe??
rhel9cis_nis_server: false
rhel9cis_sshd_clientalivecountmax: 0
rhel9cis_sshd_clientaliveinterval: 300
rhel9cis_ssh_loglevel: VERBOSE
rhel9cis_force_user_maxdays: true
rhel9cis_force_user_mindays: true
rhel9cis_force_user_warnage: true
rhel9cis_syslog: journald
rhel9cis_auditd_extra_conf_usage: true
rhel9cis_auditd_extra_conf:
  admin_space_left: '20%'  # give more time to get in to fix the issue
update_audit_template: true
rhel9cis_journal_upload_url: null
rhel9cis_journal_upload_serverkeyfile: null
rhel9cis_journal_servercertificatefile: null
rhel9cis_journal_trustedcertificatefile: null
rhel9cis_authselect_custom_profile_name: mapletree
rhel9cis_authselect_custom_profile_create: true
rhel9cis_authselect_pkg_update: true
rhel9cis_disruption_high: true
rhel9cis_dotperm_ansiblemanaged: true
# yamllint disable-line rule:line-length
rhel9cis_authselect_default_profile_to_copy: minimal --symlink-meta --symlink-pam
### disable specific rules
## filesystems
# /tmp
rhel9cis_rule_1_1_2_1_1: false
rhel9cis_rule_1_1_2_1_2: false
rhel9cis_rule_1_1_2_1_3: false
rhel9cis_rule_1_1_2_1_4: false
# /home
rhel9cis_rule_1_1_2_3_1: false
rhel9cis_rule_1_1_2_3_2: false
rhel9cis_rule_1_1_2_3_3: false
# /var
rhel9cis_rule_1_1_2_4_1: false
rhel9cis_rule_1_1_2_4_2: false
rhel9cis_rule_1_1_2_4_3: false
# /var/tmp
rhel9cis_rule_1_1_2_5_1: false
rhel9cis_rule_1_1_2_5_2: false
rhel9cis_rule_1_1_2_5_3: false
rhel9cis_rule_1_1_2_5_4: false
# /var/log
rhel9cis_rule_1_1_2_6_1: false
rhel9cis_rule_1_1_2_6_2: false
rhel9cis_rule_1_1_2_6_3: false
rhel9cis_rule_1_1_2_6_4: false
# /var/log/audit
rhel9cis_rule_1_1_2_7_1: false
rhel9cis_rule_1_1_2_7_2: false
rhel9cis_rule_1_1_2_7_3: false
rhel9cis_rule_1_1_2_7_4: false
## AIDE checks (the main disable above seems to miss some things)
rhel9cis_rule_6_1_1: false
rhel9cis_rule_6_1_2: false
rhel9cis_rule_6_1_3: false
## privilege escalation
rhel9cis_rule_5_2_4: false  # we use nopasswd sudo for automation
## off site logging (not needed now)
rhel9cis_rule_6_2_2_1_1: false
rhel9cis_rule_6_2_2_1_2: false
rhel9cis_rule_6_2_2_1_3: false
rhel9cis_rule_6_2_2_1_4: false
## false positives
rhel9cis_rule_5_4_2_5: false  # FIXME: false positive on root_path
rhel9cis_rule_1_2_1_1: false # FIXME: Bug opened on this, #292
