###
### mapletree.moe - system configuration management
### update_system - role tasks
###
---
- name: Install missing erratas
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest
    update_cache: true

- name: Install dnf utils
  ansible.builtin.dnf:
    name: 'dnf-utils'
    state: latest # noqa package-latest

- name: Autoremove
  ansible.builtin.dnf:
    autoremove: true

- name: Check for pending reboot
  ansible.builtin.command:
    cmd: needs-restarting -r
  register: reboot_required
  changed_when: "'changed' in script_res.stdout"
  failed_when: reboot_required.rc not in [0, 1]

- name: Reboot server if needed
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_required.rc == 1
