###
### mapletree.moe - system configuration management
### postfix_relay - role handlers
###
---
- name: Hash sasl_passwd file with postmap
  ansible.builtin.command: postmap /etc/postfix/sasl_passwd
  changed_when: true

- name: Hash tls_policy file with postmap
  ansible.builtin.command: postmap /etc/postfix/tls_policy
  changed_when: true

- name: Update alias database in Postfix
  ansible.builtin.command: postalias /etc/aliases
  changed_when: true

- name: Restart Postfix to apply changes
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: service_default_state | default('started') == 'started'
