###
### mapletree.moe - system configuration management
### core ansible playbook
###
---
- name: Provision any unconverted cloud servers
  ansible.builtin.import_playbook: plays/provision-cloud.yaml
- name: Run standardized server configuration.
  hosts: all
  become: true
  roles:
    # the hardening role takes an absurdly long time to process. it may be wise
    # to disable this on normal runs.
    - role: rhel9-cis
      when: lookup('env', "RUN_SECURITY")
    # - role: postfix_relay
    - role: create_users
    - role: general_config
