###
### mapletree.moe - system configuration management
### core ansible playbook
###
---
- name: Run standardized server configuration.
  hosts: servers
  roles:
    # the hardening role takes an absurdly long time to process. it may be wise
    # to disable this on normal runs.
    # - role: rhel9_cis
    #   become: true
    - role: postfix_relay
      become: true
    - role: users
      become: true
