###
### mapletree.moe - system configuration management
### core ansible playbook
###
---
- name: Run standardized server configuration.
  hosts: all
  roles:
    - role: update_system
      become: true
      # only do an unchecked update when preparing for convert2rhel
      when: ansible_distribution != "RedHat"
    - role: infra.convert2rhel.analysis
      become: true
      when: ansible_distribution != "RedHat"
    - role: infra.convert2rhel.convert
      become: true
      when: ansible_distribution != "RedHat"
    # the hardening role takes an absurdly long time to process. it may be wise
    # to disable this on normal runs.
    - role: rhel9_cis
      become: true
      when: run_security
    - role: postfix_relay
      become: true
    - role: create_users
      become: true
    - role: general_config
      become: true
