###
### mapletree.moe - system configuration management
### ansible requirements file
###
---
collections:
  - name: ansible.posix

roles:
  - name: rhel9-cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: devel  # FIXME: when 2.0 goes live change this
