###
### mapletree.moe - system configuration management
### ansible requirements file
###
---
collections:
  - name: ansible.posix
  - name: community.general
  - name: hetzner.hcloud
  - name: infra.convert2rhel

roles:
  - name: rhel9_cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: devel  # FIXME: when 2.0 goes live change this
