###
### mapletree.moe - system configuration management
### ansible requirements file
###
---
collections:
  - name: ansible.posix
  - name: community.general
  - name: fedora.linux_system_roles
  - name: hetzner.hcloud
  - name: infra.convert2rhel

roles:
  - name: giovtorres.tuned
  - name: rhel9-cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: 2.0.0
  - name: subuid_subgid
    version: v1.1.0
    src: https://github.com/rwxd/ansible-role-subuid_subgid
