###
### mapletree.moe - system configuration management
### ansible requirements file
###
---
collections:
  - name: ansible.posix
  - name: community.general
  - name: hetzner.hcloud
  - name: infra.convert2rhel

roles:
  - name: linux-system-roles.rhc
  - name: linux-system-roles.tuned
  - name: rhel9-cis
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: 2.0.0
