# code: language=ansible

###
### mapletree.moe - system configuration management
### ansible requirements file
###
---
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: containers.podman
  - name: fedora.linux_system_roles
  - name: infra.convert2rhel

roles:
  - name: giovtorres.tuned
    version: 1.1.1
  - name: rhel9-cis
    # WARNING: do NOT upgrade this module without testing it first. it can break
    #          podman rootless!
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: 2.0.0
  - name: subuid_subgid
    src: https://github.com/rwxd/ansible-role-subuid_subgid
    version: v1.1.0
