###
### mapletree.moe - system configuration management
### do a full infrastructure apply
###
---
- name: Perform full infrastructure update
  tasks:
    - name: Provision any unprovisioned cloud servers
      ansible.builtin.import_playbook: plays/provision-cloud.yaml
    - name: Apply security compliance settings
      ansible.builtin.import_playbook: plays/run-compliance.yaml
    - name: Configure system according to parameters
      ansible.builtin.import_playbook: plays/deploy-config.yaml
