###
### mapletree.moe - system configuration management
### compliance playbook - update chrony to match compliance policy
###
---
- name: COMPLIANCE | TIMESYNC | Ensure chrony matches compliance policy
  vars:
    timesync_dhcp_ntp_servers: false
    timesync_chrony_custom_settings:
      - "cmdport 0"
      - "logdir /var/log/chrony"
      - "port 0"
    timesync_ntp_provider: chrony
    timesync_ntp_servers:
      - hostname: 0.pool.ntp.org
        minpoll: 8
        maxpoll: 16
      - hostname: 1.pool.ntp.org
        minpoll: 8
        maxpoll: 16
      - hostname: 2.pool.ntp.org
        minpoll: 8
        maxpoll: 16
      - hostname: 3.pool.ntp.org
        minpoll: 8
        maxpoll: 16
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.timesync
