###
### mapletree.moe - system configuration management
### compliance playbook - use cis lvl 2 server as basis for local policy
###
---
#
# NOTE: this execution of the benchmark is extremely aggressive and assumes it
#       will only be ran on servers adhering to the `mapletree.moe` config style
#
- name: COMPLIANCE | BENCHMARK | Run CIS server level 2 benchmark
  vars:
    rhel9cis_set_boot_pass: false  # handled in `compliance_bootloader.yaml`
    rhel9cis_ipv6_required: false  # FIXME: implement ipv6
    rhel9cis_sshd_allowusers: "admin podman" # FIXME: move to group based allow
    rhel9cis_sshd_clientalivecountmax: 1 # ensure sshd_config passes oscap
    rhel9cis_sshd_clientaliveinterval: 300
    rhel9cis_ssh_loglevel: VERBOSE
    rhel9cis_authselect_custom_profile_name: mapletree # must be set for role
    # yamllint disable-line rule:line-length
    rhel9cis_authselect_default_profile_to_copy: minimal --symlink-meta --symlink-pam
    rhel9cis_authselect_pkg_update: true
    rhel9cis_disruption_high: true
    rhel9cis_dotperm_ansiblemanaged: true
    rhel9cis_flush_ipv4_route: true
    rhel9cis_flush_ipv6_route: false # FIXME: ipv6
    rhel9cis_sysctl_update: true
    rhel9cis_aide_scan: cron # FIXME: transition to using systemd timers
    rhel9cis_auditd_extra_conf_usage: true
    rhel9cis_auditd_extra_conf:
      admin_space_left: '10%' # should never be hit, if so halt system
      space_left: '20%'  # give more time to get in to clear space
    rhel9cis_auditd_space_left_action: email # notify when space is low
    rhel9cis_journald_systemkeepfree: 20G
    rhel9cis_journald_runtimekeepfree: 20G
    rhel9cis_syslog: journald # prefer journald as its already present
    rhel9cis_rule_1_1_2_1_1: false # rules 1.1.2.x are for dedicated partitions
    rhel9cis_rule_1_1_2_1_2: false # which we don't use
    rhel9cis_rule_1_1_2_1_3: false
    rhel9cis_rule_1_1_2_1_4: false
    rhel9cis_rule_1_1_2_3_1: false
    rhel9cis_rule_1_1_2_3_2: false
    rhel9cis_rule_1_1_2_3_3: false
    rhel9cis_rule_1_1_2_4_1: false
    rhel9cis_rule_1_1_2_4_2: false
    rhel9cis_rule_1_1_2_4_3: false
    rhel9cis_rule_1_1_2_5_1: false
    rhel9cis_rule_1_1_2_5_2: false
    rhel9cis_rule_1_1_2_5_3: false
    rhel9cis_rule_1_1_2_5_4: false
    rhel9cis_rule_1_1_2_6_1: false
    rhel9cis_rule_1_1_2_6_2: false
    rhel9cis_rule_1_1_2_6_3: false
    rhel9cis_rule_1_1_2_6_4: false
    rhel9cis_rule_1_1_2_7_1: false
    rhel9cis_rule_1_1_2_7_2: false
    rhel9cis_rule_1_1_2_7_3: false
    rhel9cis_rule_1_1_2_7_4: false
    rhel9cis_rule_1_2_1_1: false # FIXME: false positive, issue #292
    rhel9cis_rule_5_2_4: false  # rule 5.2.4 breaks w/NO_PASSWD + locked psswd
    rhel9cis_rule_5_4_2_5: false  # FIXME: false positive on root_path
    rhel9cis_rule_6_2_2_1_1: false # rules 6.2.2.1.x configures offsite logging
    rhel9cis_rule_6_2_2_1_2: false # which we don't use
    rhel9cis_rule_6_2_2_1_3: false
    rhel9cis_rule_6_2_2_1_4: false
  ansible.builtin.include_role:
    name: rhel9-cis
