###
### mapletree.moe - system configuration management
### configuration playbook - deploy openzfs using kmod tracking
###
---
- name: CONFIGURE | ZFS | Install OpenZFS Public Key
  ansible.builtin.rpm_key:
    # yamllint disable-line rule:line-length
    key: https://raw.githubusercontent.com/zfsonlinux/zfsonlinux.github.com/master/zfs-release/RPM-GPG-KEY-openzfs-key2
    fingerprint: 7DC7 299D CF7C 7FD9 CD87 701B A599 FD5E 9DB8 4141
    state: present
- name: CONFIGURE | ZFS | Install OpenZFS `zfs-release` package
  ansible.builtin.dnf:
    # UPGRADE: change this on upgrade
    name: https://zfsonlinux.org/epel/zfs-release-2-3.el9.noarch.rpm
    state: present
- name: CONFIGURE | ZFS | Disable DKMS zfs repository
  community.general.dnf_config_manager:
    name: zfs
    state: disabled
- name: CONFIGURE | ZFS | Enable kABI kmod zfs repository
  community.general.dnf_config_manager:
    name: zfs-kmod
    state: enabled
- name: CONFIGURE | ZFS | Install `zfs` package from `zfs-kmod` repository
  ansible.builtin.dnf:
    name: zfs
    state: present
- name: CONFIGURE | ZFS | Enable `zfs-kmod` kernel modules to auto-load on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/zfs.conf
    content: "zfs"
    owner: root
    group: root
    mode: "0644"
