###
### mapletree.moe - system configuration management
### configuration playbook - deploy network configuration
###
---
- name: CONFIGURE | NETWORK | Enable DHCP and set static DNS servers
  vars:
    network_provider: nm
    network_state:
      interfaces:
        - name: "{{ ansible_default_ipv4.interface }}"
          type: ethernet
          state: up
          ipv4:
            enabled: true
            auto-dns: false
            auto-gateway: true
            auto-routes: true
            dhcp: true
          ipv6:
            enabled: false # FIXME: enable ipv6
            auto-dns: false
            auto-gateway: false
            auto-routes: false
            autoconf: false
            dhcp: false
      dns-resolver:
        config:
          server:
            - 1.1.1.1
            - 1.0.0.1
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.network
# FIXME: this is an ugly hack because we don't have ipv6
# - name: CONFIGURE | NETWORK | Remove ipv6 localhost from /etc/hosts
#   ansible.builtin.lineinfile:
#     dest: /etc/hosts
#     regexp: ^::1
#     state: absent
