###
### mapletree.moe - system configuration management
### configuration playbook - deploy system packages
###
---
- name: CONFIGURE | PACKAGES | Install standard packages
  ansible.builtin.package:
    name:
      - container-selinux
      - dnf-automatic
      - git
      - podman
      - tmux
    state: present
    update_cache: true
- name: CONFIGURE | PACKAGES | Configure automatic updates
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} = {{ item.value }}'
  with_items:
    - name: upgrade_type
      value: security
    - name: download_updates
      value: 'yes'
    - name: apply_updates
      value: 'yes'
    - name: reboot
      value: 'when-needed'
- name: CONFIGURE | PACKAGES | Enable automatic security updates
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: started
    enabled: true
