###
### mapletree.moe - system configuration management
### user configuration task
###
---
- name: Ensure user configuration has been completed
  block:
    - name: Ensure 'admin' group exists with GID '1001'
      ansible.builtin.group:
        name: admin
        gid: 1001
        state: present
    - name: Ensure 'podman' group exists with GID '1000'
      ansible.builtin.group:
        name: podman
        gid: 1000
        state: present
    - name: Ensure 'users' group exists with GID '100'
      ansible.builtin.group:
        name: users
        gid: 100
        state: present
    - name: Ensure 'wheel' group exists with GID '10'
      ansible.builtin.group:
        name: wheel
        gid: 10
        state: present
    - name: Ensure user "admin" exists with UID '1001' and is locked
      ansible.builtin.user:
        name: admin
        comment: Mapletree.moe Administrator
        uid: 1001
        group: admin
        password_lock: true
        groups: admin,users,wheel
        state: present
    - name: Ensure user "podman" exists with UID '1000' and is locked
      ansible.builtin.user:
        name: podman
        comment: Mapletree.moe Container User
        uid: 1000
        group: podman
        password_lock: true
        groups: podman,users
        state: present
    - name: Ensure user "root" is locked
      ansible.builtin.user:
        name: root
        password_lock: true
    - name: Set up authorized_keys for user "admin"
      ansible.posix.authorized_key:
        user: admin
        state: present
        key: '{{ item }}'
      with_items: "{{ admin_authorized_keys }}"
    - name: Enable linger for "podman" user
      ansible.builtin.command:
        cmd: "loginctl enable-linger podman"
        creates: "/var/lib/systemd/linger/podman"
