###
### mapletree.moe - system configuration management
### configure network using `network_state` to allow for declarative format
###
---
- name: Ensure network uses DHCP on primary interface with static DNS servers
  vars:
    network_provider: nm
    network_state:
      interfaces:
        - name: "{{ ansible_default_ipv4.interface }}"
          type: ethernet
          state: up
          ipv4:
            enabled: true
            auto-dns: false
            auto-gateway: true
            auto-routes: true
            dhcp: true
          ipv6:
            enabled: false # FIXME: enable ipv6
            auto-dns: false
            auto-gateway: false
            auto-routes: false
            autoconf: false
            dhcp: false
      dns-resolver:
        config:
          server:
            - 1.1.1.1
            - 1.0.0.1
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.network
