###
### mapletree.moe - system configuration management
### manage podman deployed services across multiple systems
###
---
- name: Ensure podman.socket is running for podman user
  become: false
  remote_user: podman
  ansible.builtin.systemd_service:
    name: podman.socket
    enabled: true
    state: started
    scope: user
