###
### mapletree.moe - system configuration management
### configure postfix to act as a simple local mail forwarder
###
---
- name: Ensure SMTP Authentication mechanisms are present for Postfix
  ansible.builtin.package:
    name: cyrus-sasl-plain # NOTE: smtp2go requirement, change for others
    state: present
- name: Ensure Postfix is installed and configured for mail forwarding
  vars:
    postfix_conf:
      # NOTE: these may need to be changed according to relayhost requirements
      inet_interfaces: "loopback-only" # do not allow external connections
      mydestination: "" # null configuration, handle routing with virtual maps
      relayhost: "{{ postfix_relayhost }}" # send all mail through external srvr
      sender_canonical_classes: "envelope_sender, header_sender"
      sender_canonical_maps: "regexp:/etc/postfix/sender_canonical_maps"
      smtp_header_checks: "regexp:/etc/postfix/smtp_header_checks"
      smtp_sasl_auth_enable: "yes"
      smtp_sasl_password_maps: "hash:/etc/postfix/sasl_passwd"
      smtp_sasl_security_options: "noanonymous"
      smtp_sasl_tls_security_options: "noanonymous"
      smtp_tls_policy_maps: "hash:/etc/postfix/tls_policy"
      smtp_use_tls: "yes"
      smtpd_client_restrictions: "permit_mynetworks,reject"
      virtual_maps: "regexp:/etc/postfix/virtual_regexp"
    postfix_files:
      - name: sasl_passwd
        # username and password to access smtp relay
        content: "{{ postfix_sasl_passwd }}"
        postmap: true
      - name: sender_canonical_maps
        # rewrites sender address to allow for mail to pass through relayhost
        content: "/.+/ {{ ansible_hostname }}@{{ ansible_domain }}"
      - name: smtp_header_checks
        # rewrites headers to make mail appear to genuinely be from sender addr
        # yamllint disable-line rule:line-length
        content: "/^From:.*/ REPLACE From: {{ ansible_hostname }}@{{ ansible_domain }}"
      - name: tls_policy
        content: "{{ postfix_tls_policy }}"
        postmap: true
      - name: virtual_regexp
        # rewrite the "TO:" address of all emails to point towards administrator
        content: "/.+@.+/ {{ postfix_external_email }}"
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.postfix
