###
### mapletree.moe - system configuration management
### provisioning playbook - unrestricted upgrade of all packages to latest
###
---
#
# NOTE: this task is required because unless the system has been fully upgraded
#       there is a high likelyhood `infra.convert2rhel` will fail due to lack
#       of replacement packages.
#
- name: Update all installed packages to the latest version in the repo
  ansible.builtin.package:
    name: '*'
    state: latest # noqa package-latest
    update_cache: true
- name: Install dnf-utils to check for restarts
  ansible.builtin.dnf:
    name: 'dnf-utils'
    state: latest # noqa package-latest
- name: Remove any packages that have been orphaned by the update
  ansible.builtin.dnf:
    autoremove: true
- name: Check if a reboot is required before conversion
  ansible.builtin.command:
    cmd: needs-restarting -r
  register: reboot_required
  changed_when: true
  failed_when: reboot_required.rc not in [0, 1]
- name: Reboot the server if required
  ansible.builtin.reboot:
    reboot_timeout: 600
  when: reboot_required.rc == 1
