###
### mapletree.moe - system configuration management
### provisioning playbook - GPG key cleanup and prune orphaned packages
###
---
# TODO: this should be done by the convert2rhel script, why is it not?
- name: PROVISION | POST | Remove AlmaLinux GPG key from RPM Key Registry
  ansible.builtin.rpm_key:
    key: http://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux-9
    state: absent
- name: PROVISION | POST | Remove RockyLinux GPG key from RPM Key Registry
  ansible.builtin.rpm_key:
    key: https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-9
    state: absent
- name: PROVISION | POST | Remove orphaned packages
  ansible.builtin.dnf:
    autoremove: true
