# code: language=ansible

###
### mapletree.moe - system configuration management
### hardening role - bootloader - configure system bootloader
###
---
- name: HARDENING | BOOTLOADER | Configure bootloader
  vars:
    # set hardening_bootloader_password in group_vars
    bootloader_password: "{{ hardening_bootloader_password }}"
    bootloader_reboot_ok: true
    bootloader_settings:
      - kernel: ALL
        options:
          - name: slub_debug # freed memory poisoning (DISA STIG)
            value: P
          - name: page_poison # freed memory poisoning (DISA STIG)
            value: 1
          - name: vsyscall # disable virtual syscalls (DISA STIG)
            value: none
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_bootloader/
    name: fedora.linux_system_roles.bootloader

- name: HARDENING | BOOTLOADER | Flush bootloader handlers
  ansible.builtin.meta: flush_handlers
