# code: language=ansible

###
### mapletree.moe - system configuration management
### hardening role - configure system to align with compliance policy
###
---
- name: HARDENING | Run ansible-lockdown CIS Level 2 Server benchmark
  ansible.builtin.include_tasks:
    file: benchmark.yaml

- name: HARDENING | Configure bootloader
  ansible.builtin.include_tasks:
    file: bootloader.yaml

- name: HARDENING | Configure firewall
  ansible.builtin.include_tasks:
    file: firewall.yaml

- name: HARDENING | Configure kernel security settings
  ansible.builtin.include_tasks:
    file: kernel.yaml

- name: HARDENING | Configure system packages
  ansible.builtin.include_tasks:
    file: packages.yaml

- name: HARDENING | Configure additional system security settings
  ansible.builtin.include_tasks:
    file: general.yaml

- name: HARDENING | Configure SSH Server
  ansible.builtin.include_tasks:
    file: sshd.yaml

- name: HARDENING | Configure system services
  ansible.builtin.include_tasks:
    file: systemd.yaml

- name: HARDENING | Configure system time
  ansible.builtin.include_tasks:
    file: timesync.yaml
