# code: language=ansible

###
### mapletree.moe - system configuration management
### hardening role - packages - configure system packages & package manager
###
---
- name: HARDENING | PACKAGES | Enable local package gpg key verification
  community.general.ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: localpkg_gpgcheck
    value: 1
    no_extra_spaces: true
    create: true
    mode: "0644"

- name: HARDENING | PACKAGES | Install packages needed for compliance
  ansible.builtin.package:
    name:
      - audispd-plugins
      - gnutls-utils
      - libreswan
      - nss-tools
      - policycoreutils-python-utils
      - rng-tools
      - rsyslog-gnutls
      - s-nail
    state: present
