# code: language=ansible

###
### mapletree.moe - system configuration management
### hardening role - sshd - lockdown secure shell access
###
---
- name: HARDENING | SSHD | Generate new compliant SSH host keys
  # Generate new SSH keys to comply with the new policy.
  # Required for the next task to succeed.
  block:
    - name: SSHD | HOST KEYS | Ensure host has compliant 4096 bit RSA key
      community.crypto.openssh_keypair:
        group: root
        mode: "0600"
        owner: root
        path: /etc/ssh/ssh_host_rsa_key
        regenerate: full_idempotence
        size: 4096
        state: present
        type: rsa

    - name: SSHD | HOST KEYS | Ensure host has compliant ed25519 key
      community.crypto.openssh_keypair:
        group: root
        mode: "0600"
        owner: root
        path: /etc/ssh/ssh_host_ed25519_key
        regenerate: full_idempotence
        state: present
        type: ed25519

# it won't be used in our new configuration and could cause weird issues if the
# next role detects it's present.
- name: HARDENING | SSHD | Delete the sshd_config includes folder
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: absent

- name: HARDENING | SSHD | Configure SSHD to align with policy
  vars:
    sshd_config:
      # yamllint disable rule:line-length
      AllowUsers: mapletree
      Banner: /etc/issue.net
      Ciphers: aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-gcm@openssh.com,aes128-ctr
      ClientAliveInterval: 300
      ClientAliveCountMax: 1
      Compression: false # DISA STIG
      DenyUsers: nobody
      DisableForwarding: true
      GSSAPIAuthentication: false
      HostbasedAuthentication: false
      # most profiles require chacha20-poly1305 as well, but disable due to
      # terrapin vuln (CVE-2023-48795)
      HostKeyAlgorithms: ssh-ed25519,rsa-sha2-512,rsa-sha2-256
      HostKey:
        - /etc/ssh/ssh_host_ed25519_key
        - /etc/ssh/ssh_host_rsa_key
      IgnoreRhosts: true
      IgnoreUserKnownHosts: true
      KerberosAuthentication: false
      KexAlgorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
      ListenAddress:
        - 0.0.0.0 # IPV6: enable here as well
      LoginGraceTime: 0 # regreSSHion (CVE-2024-6387) fix
      LogLevel: VERBOSE # CIS Level 2 & DISA STIG
      MACs: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
      MaxAuthTries: 4
      MaxSessions: 4
      MaxStartups: 10:30:60
      PermitEmptyPasswords: false
      PermitRootLogin: false
      PermitUserEnvironment: false
      PrintLastLog: true
      PubkeyAuthentication: true
      RekeyLimit: 1G 1h
      RequiredRSASize: 4096
      StrictModes: true
      Subsystem: sftp /usr/libexec/openssh/sftp-server
      UsePAM: true
      X11UseLocalhost: true
      # yamllint enable rule:line-length
    sshd_config_file: /etc/ssh/sshd_config
    sshd_config_owner: root
    sshd_config_group: root
    sshd_config_mode: "0600"
    sshd_manage_firewall: true
    sshd_manage_selinux: true
    sshd_skip_defaults: true
    sshd_sysconfig: true
    sshd_sysconfig_override_crypto_policy: true # this policy is stricter
    sshd_sysconfig_use_strong_rng: true
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_sshd/
    name: fedora.linux_system_roles.sshd

- name: HARDENING | SSHD | Flush sshd handlers
  ansible.builtin.meta: flush_handlers
