###
### mapletree.moe - system configuration management
### configuration playbook - deploy users and groups and configure settings
###
---
- name: CONFIGURE | GROUPS | Ensure group 'admin' - GID '1001' exists
  ansible.builtin.group:
    name: admin
    gid: 1001
    state: present
- name: CONFIGURE | GROUPS | Ensure group 'podman' - GID '1000' exists
  ansible.builtin.group:
    name: podman
    gid: 1000
    state: present
- name: CONFIGURE | GROUPS | Ensure group 'users' - GID '100' exists
  ansible.builtin.group:
    name: users
    gid: 100
    state: present
- name: CONFIGURE | GROUPS | Ensure group 'wheel' - GID '10' exists
  ansible.builtin.group:
    name: wheel
    gid: 10
    state: present
- name: CONFIGURE | USERS | Ensure user "admin" - UID '1001' - locked exists
  ansible.builtin.user:
    name: admin
    comment: Mapletree.moe Administrator
    uid: 1001
    group: admin
    password_lock: true
    groups: admin,users,wheel
    state: present
- name: CONFIGURE | USERS | Ensure user "podman" - UID '1000' - locked exists
  ansible.builtin.user:
    name: podman
    comment: Mapletree.moe Container User
    uid: 1000
    group: podman
    password_lock: true
    groups: podman,users
    state: present
- name: CONFIGURE | USERS | Ensure user "root" is locked to prevent login
  ansible.builtin.user:
    name: root
    password_lock: true
- name: CONFIGURE | USERS | ADMIN | Set up ssh authorized_keys
  ansible.posix.authorized_key:
    user: admin
    state: present
    key: '{{ item }}'
  with_items: "{{ admin_authorized_keys }}"
- name: CONFIGURE | USERS | PODMAN | Set up ssh authorized_keys
  ansible.posix.authorized_key:
    user: admin
    state: present
    key: '{{ item }}'
  with_items: "{{ podman_authorized_keys }}"
- name: CONFIGURE | USERS | PODMAN | Enable systemd linger for user
  ansible.builtin.command:
    cmd: "loginctl enable-linger podman"
    creates: "/var/lib/systemd/linger/podman"
- name: CONFIGURE | USERS | PODMAN | Generate subuids
  vars:
    subid_users: # noqa var-naming
      - podman
  ansible.builtin.include_role:
    name: subuid_subgid
# FIXME: use a handler
- name: CONFIGURE | USERS | Reboot the server to apply lingering
  ansible.builtin.reboot:
    reboot_timeout: 600
