# code: language=ansible

###
### mapletree.moe - system configuration management
### ansible group variables
###
---
### common role configuration variables
# redhat credentials
common_redhat_key: "{{ vault_common_redhat_key }}"
common_redhat_org: "{{ vault_common_redhat_org }}"
common_redhat_pass: "{{ vault_common_redhat_pass }}"
common_redhat_user: "{{ vault_common_redhat_user }}"
# postfix null-relay configuration
common_relay_sasl: "cyrus-sasl-plain"
common_relay_host: "mail.smtp2go.com"
common_relay_port: "587"
common_relay_user: "{{ vault_common_relay_user }}"
common_relay_pass: "{{ vault_common_relay_pass }}"
common_mapletree_authorized_keys:
  # yamllint disable-line rule:line-length
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKuYlqIG3fsTfKt5xmvbzgxIp1pzh2xiJXGtyBo41DJB nagato@mapletree.com"
  # yamllint disable-line rule:line-length
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYfs1EndYHRh5WcW+jkuD7IKSvZZHM+OTqDX0RuYlY5 yuki@murasame"

### hardening role configuration variables
hardening_bootloader_password: "{{ vault_hardening_bootloader_password }}"

#
# global container configuration
#
containers_authelia_smtp_host: mail.smtp2go.com
containers_authelia_smtp_port: 587
containers_authelia_smtp_user: "{{ vault_common_relay_user }}"
containers_authelia_smtp_pass: "{{ vault_common_relay_pass }}"
containers_lldap_base_dn_domain: mapletree
containers_lldap_base_dn_extension: moe
# yamllint disable-line rule:line-length
containers_lldap_discord_bot_token: "{{ vault_containers_lldap_discord_bot_token }}"

###
### Container Secrets Section
###
# yamllint disable-line rule:line-length
containers_traefik_dashboard_password: "{{ vault_containers_traefik_dashboard_password }}"
