###
### mapletree.moe - system configuration management
### ansible group variables
###
---
## general
bootloader_password: "{{ vault_bootloader_password }}"

## redhat
redhat_activation_key: "{{ vault_redhat_activation_key }}"
redhat_organization: "{{ vault_redhat_organization }}"

## ssh keys
admin_authorized_keys:
  # yamllint disable-line rule:line-length
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEYfs1EndYHRh5WcW+jkuD7IKSvZZHM+OTqDX0RuYlY5 yuki@murasame"

## postfix variables
postfix_relayhost: "[mail.smtp2go.com]:587"
postfix_external_email: "{{ vault_postfix_external_email }}"
postfix_sasl_passwd: "{{ vault_postfix_sasl_passwd }}"
postfix_tls_policy: "[mail.smtp2go.com]:587 encrypt"
