###
### mapletree.moe - system configuration management
### create_users - role tasks
###
---
- name: Ensure group 'admin' exists
  ansible.builtin.group:
    name: admin
    state: present

- name: Ensure group 'user' exists
  ansible.builtin.group:
    name: containers
    state: present

- name: Ensure group 'containers' exists
  ansible.builtin.group:
    name: users
    state: present

- name: Ensure group 'wheel' exists
  ansible.builtin.group:
    name: wheel
    state: present

- name: Ensure user "admin" exists and is correct
  ansible.builtin.user:
    name: admin
    comment: Mapletree.moe Administrator
    uid: 1001
    group: admin
    # yamllint disable-line rule:line-length
    password: "{{ create_users_admin_password | password_hash('sha512', create_users_password_salt) }}"
    groups: admin,users,wheel
    state: present

- name: Ensure user "containers" exists and is correct
  ansible.builtin.user:
    name: containers
    comment: Container User
    uid: 1000
    group: containers
    # yamllint disable-line rule:line-length
    password: "{{ create_users_containers_password | password_hash('sha512', create_users_password_salt) }}"
    groups: containers,users
    state: present

- name: Set root Password
  ansible.builtin.user:
    name: root
    # yamllint disable-line rule:line-length
    password: "{{ create_users_root_password | password_hash('sha512', create_users_password_salt) }}"

- name: Set up authorized_keys for user "admin"
  ansible.posix.authorized_key:
    user: admin
    state: present
    key: '{{ item }}'
  with_items: "{{ create_users_admin_authorized_keys }}"

- name: Enable linger for "containers" user
  ansible.builtin.command:
    cmd: "loginctl enable-linger containers"
    creates: "/var/lib/systemd/linger/containers"
  notify:
    - Reboot System
