###
### mapletree.moe - system configuration management
### create_users - role tasks
###
---
- name: Ensure group 'admin' exists
  ansible.builtin.group:
    name: admin
    state: present

- name: Ensure group 'user' exists
  ansible.builtin.group:
    name: containers
    state: present

- name: Ensure group 'containers' exists
  ansible.builtin.group:
    name: users
    state: present

- name: Ensure group 'wheel' exists
  ansible.builtin.group:
    name: wheel
    state: present

- name: Ensure group "docker" exists with correct gid
  ansible.builtin.group:
    name: docker
    state: present
    gid: 1750

- name: Ensure user "admin" exists and is correct
  ansible.builtin.user:
    name: admin
    comment: Mapletree.moe Administrator
    uid: 1001
    group: admin
    groups: admin,docker,users,wheel

- name: Ensure user "containers" exists and is correct
  ansible.builtin.user:
    name: containers
    comment: Container User
    uid: 1000
    group: containers
    groups: containers,docker,users

- name: Set up authorized_keys for user "admin"
  ansible.posix.authorized_key:
    user: admin
    state: present
    key: '{{ item }}'
  with_items: "{{ create_users_admin_authorized_keys }}"
