###
### mapletree.moe - system configuration management
### compliance playbook - password protect bootloader and configure boot options
###
---
- name: COMPLIANCE | BOOTLOADER | Set password & harden kernel command line
  vars:
    # set bootloader_password in group_vars
    bootloader_settings:
      - kernel: ALL
        options:
          - name: slub_debug
            value: P
          - name: page_poison
            value: 1
          - name: vsyscall
            value: none
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.bootloader
