###
### mapletree.moe - system configuration management
### postfix_relay - role variables
###
---
# NOTE: ALL mail for the system will be redirected to this address. This could
#       be dangerous. Ensure `mydestination` is set correctly.
postfix_relay_external_email: "admin@xample.com"
postfix_relay_relayhost: "[smtp.example.com]:587"
postfix_relay_sasl_passwd: "[smtp.example.com]:587 username:password"
postfix_relay_tls_policy: "[smtp.example.com]:587 encrypt"
postfix_relay_sender_canonical_maps: "/.+/ host@example.com"
postfix_relay_smtp_header_checks: "/^From:.*/ REPLACE From: host@example.com"

postfix_relay_conf:
  inet_interfaces: "loopback-only"
  mydestination: ""
  relayhost: "{{ postfix_relay_relayhost }}"
  sender_canonical_classes: "envelope_sender, header_sender"
  sender_canonical_maps: "regexp:/etc/postfix/sender_canonical_maps"
  smtp_header_checks: "regexp:/etc/postfix/smtp_header_checks"
  smtp_sasl_auth_enable: "yes"
  smtp_sasl_password_maps: "hash:/etc/postfix/sasl_passwd"
  smtp_sasl_security_options: "noanonymous"
  smtp_sasl_tls_security_options: "noanonymous"
  smtp_tls_policy_maps: "hash:/etc/postfix/tls_policy"
  smtp_use_tls: "yes"
  smtpd_client_restrictions: "permit_mynetworks,reject"
  virtual_maps: "regexp:/etc/postfix/virtual_regexp"
