###
### mapletree.moe - system configuration management
### postfix_relay - role tasks
###
---
- name: Redirect all root email to administrator
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    line: "{{ postfix_relay_root_email }}"
    regexp: "^root:"
  notify:
    - Update alias database in Postfix
    - Restart Postfix to apply changes
