###
### mapletree.moe - system configuration management
### postfix_relay - role tasks
###
---
- name: Ensure SMTP Authentication mechanisms are present for Postfix
  # NOTE: this will need to be changed for different smtp providers
  ansible.builtin.package:
    name:
      - cyrus-sasl # base requirement
      - cyrus-sasl-plain # smtp2go requirement
    state: present
# - name: Ensure forwarding is set up for local users in /etc/aliases
#   # TODO: can this be integrated with fedora.linux_system_roles.postfix throug
#   #       the use of `postfix_files`?
#   ansible.builtin.lineinfile:
#     path: /etc/aliases
#     owner: root
#     group: root
#     mode: "0644"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#   with_items:
#     - line: "admin: root"
#       regexp: "^admin:"
#     - line: "podman: root"
#       regexp: "^podman:"
#     - line: "{{ postfix_relay_root_email }}"
#       regexp: "^root:"
#   notify:
#     - Update Postfix alias database
- name: Ensure Postfix is installed and configured for mail forwarding
  # NOTE: fedora system roles are better maintained and have more features
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.postfix
  vars:
    postfix_conf: "{{ postfix_relay_conf }}"
    postfix_files:
      - name: sasl_passwd
        content: "{{ postfix_relay_sasl_passwd }}"
        postmap: true
      - name: sender_canonical_maps
        content: "{{ postfix_relay_sender_canonical_maps }}"
      - name: smtp_header_checks
        content: "{{ postfix_relay_smtp_header_checks }}"
      - name: tls_policy
        content: "{{ postfix_relay_tls_policy }}"
        postmap: true
      - name: virtual_regexp
        content: "/.+@.+/ {{ postfix_relay_external_email }}"
