# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - authela - deploy authelia to target system
###
---
- name: CONTAINERS | AUTHELIA | Check dependencies
  when: "'traefik' not in containers_services_enabled or
         'lldap' not in containers_services_enabled"
  ansible.builtin.fail:
    # yamllint disable rule:line-length
    msg: |
      !!!ERROR!!!
      !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/tasks/authelia.yaml:9
      !!!ERROR!!! authelia has unsatisfied dependencies. please review.
      !!!ERROR!!!
    # yamllint enable rule:line-length

- name: CONTAINERS | AUTHELIA | Generate secrets
  # while we generate new secrets in this step, they are NOT deployed later
  # unless they are needed
  ansible.builtin.set_fact:
    # yamllint disable rule:line-length
    authelia_encryption_key: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    authelia_oidc_hmac_secret: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    authelia_reset_password_jwt_secret: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    authelia_session_secret: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    # yamllint enable rule:line-length

- name: CONTAINERS | AUTHELIA | Install configuration file
  block:
    - name: CONTAINERS | AUTHELIA | FILES | Create configuration directory
      ansible.builtin.file:
        path: /home/podman/containers/config/authelia
        state: directory
        owner: podman
        group: podman
        mode: "0755"
    - name: CONTAINERS | AUTHELIA | FILES | Template configuration file
      ansible.builtin.template:
        src: config/authelia/config.yaml.j2
        dest: /home/podman/containers/config/authelia/config.yaml
        owner: podman
        group: podman
        mode: "0640"

- name: CONTAINERS | AUTHELIA | Install container
  vars:
    podman_quadlet_specs:
      # list order determined by dependencies - do NOT modify
      - name: authelia-db
        type: volume
        template_src: authelia/db.volume.j2
      - name: authelia-db
        type: container
        template_src: authelia/db.container.j2
      - name: authelia-redis
        type: volume
        template_src: authelia/redis.volume.j2
      - name: authelia-redis
        type: container
        template_src: authelia/redis.container.j2
      - name: authelia
        type: container
        template_src: authelia/main.container.j2
    podman_secrets:
      - name: authelia-encryption-key
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ authelia_encryption_key }}"
      - name: authelia-session-secret
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ authelia_session_secret }}"
      - name: authelia-oidc-hmac-secret
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ authelia_oidc_hmac_secret }}"
      - name: authelia-reset-password-jwt-secret
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ authelia_reset_password_jwt_secret }}"
      - name: authelia-smtp-password
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ containers_authelia_smtp_pass }}"
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
    name: fedora.linux_system_roles.podman

- name: CONTAINERS | AUTHELIA | Append database information to automated backup
  vars:
    authelia_db:
      - type: pgsql
        host: authelia-db
        name: authelia
        user: authelia
        pass: authelia
  ansible.builtin.set_fact:
    containers_database_list: "{{ containers_database_list + authelia_db }}"
