# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - authela - deploy authelia to target system
###
---
- name: CONTAINERS | AUTHELIA | Check dependencies
  block:
    - name: CONTAINERS | AUTHELIA | Check dependencies - traefik
      ansible.builtin.fail:
        # yamllint disable rule:line-length
        msg: |
          !!!ERROR!!!
          !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/authelia.yaml:21
          !!!ERROR!!! traefik is a hard dependency of authelia.
          !!!ERROR!!! you must add it to `containers_services_enabled` before the
          !!!ERROR!!! declaration of authelia.
          !!!ERROR!!!
        # yamllint enable rule:line-length
      when: "'traefik' not in containers_services_enabled"
    - name: CONTAINERS | AUTHELIA | Check dependencies - lldap
      ansible.builtin.fail:
        # yamllint disable rule:line-length
        msg: |
          !!!ERROR!!!
          !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/authelia.yaml:33
          !!!ERROR!!! lldap is a hard dependency of authelia.
          !!!ERROR!!! you must add it to `containers_services_enabled` before the
          !!!ERROR!!! declaration of authelia.
          !!!ERROR!!!
        # yamllint enable rule:line-length
      when: "'lldap' not in containers_services_enabled"

- name: CONTAINERS | AUTHELIA | Generate secrets
  # while we generate new secrets in this step, they are NOT deployed later
  # unless they are needed
  ansible.builtin.set_fact:
    # yamllint disable rule:line-length
    authelia_encryption_key: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    # yamllint enable rule:line-length

- name: CONTAINERS | AUTHELIA | Install configuration file
  block:
    - name: CONTAINERS | AUTHELIA | FILES | Create configuration directory
      ansible.builtin.file:
        path: /home/podman/containers/authelia
        state: directory
        owner: podman
        group: podman
        mode: "0755"
    - name: CONTAINERS | AUTHELIA | FILES | Template configuration file
      ansible.builtin.template:
        src: authelia/config.yaml.j2
        dest: /home/podman/containers/authelia/config.yaml
        owner: podman
        group: podman
        mode: "0640"

- name: CONTAINERS | AUTHELIA | Configure podman
  block:
    - name: CONTAINERS | AUTHELIA | PODMAN | Install containers
      vars:
        podman_fail_if_too_old: true
        podman_quadlet_specs:
          # list order determined by dependencies - do NOT modify
          - template_src: authelia-db.volume.j2
          - template_src: authelia-db.container.j2
          - template_src: authelia-redis.volume.j2
          - template_src: authelia-redis.container.j2
          - template_src: authelia.container.j2
        podman_prune_images: true
        podman_pull_image: true
        podman_run_as_user: podman
        podman_run_as_group: podman
        podman_secrets:
          - name: authelia-encryption-key
            state: present
            skip_existing: true # do not overwrite if secret exists
            data: "{{ authelia_encryption_key }}"
          - name: authelia-smtp-password
            state: present
            skip_existing: true # do not overwrite if secret exists
            data: "{{ containers_authelia_smtp_pass }}"
        podman_validate_certs: true
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
        name: fedora.linux_system_roles.podman

    - name: CONTAINERS | AUTHELIA | PODMAN | Flush podman handlers
      ansible.builtin.meta: flush_handlers
