# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - db-backup - deploy automated db backup system
###
---
- name: CONTAINERS | DB BACKUP | Deploy automated database backups
  vars:
    podman_quadlet_specs:
      - template_src: db-backup.container.j2
    podman_secrets:
      - name: db-backup-rocketchat-webhook-url
        state: present
        skip_existing: false # allow updates
        data: "{{ containers_db_backup_rocketchat_webhook_url }}"
      - name: db-backup-s3-key-id
        state: present
        skip_existing: false # allow for key rotation
        data: "{{ containers_db_backup_s3_key_id }}"
      - name: db-backup-s3-key-secret
        state: present
        skip_existing: false # allow for key rotation
        data: "{{ containers_db_backup_s3_key_secret }}"
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
    name: fedora.linux_system_roles.podman
