# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - lldap - deploy lldap to target system
###
---
- name: CONTAINERS | LLDAP | Check dependencies
  when: "'traefik' not in containers_services_enabled"
  ansible.builtin.fail:
    # yamllint disable rule:line-length
    msg: |
      !!!ERROR!!!
      !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/tasks/lldap.yaml:9
      !!!ERROR!!! lldap has unsatisfied dependencies. please review.
      !!!ERROR!!!
    # yamllint enable rule:line-length

- name: CONTAINERS | LLDAP | Generate secrets
  # here we generate new secrets but we wont deploy unless needed.
  ansible.builtin.set_fact:
    # yamllint disable rule:line-length
    lldap_bind_user_pass: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    lldap_jwt_secret: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    lldap_key_seed: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    lldap_ldap_user_pass: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    lldap_password_manager_pass: "{{ lookup('community.general.random_string', special=false, length=64) }}"
    # yamllint enable rule:line-length

- name: CONTAINERS | LLDAP | Deploy files for automated bootstrapping
  block:
    - name: CONTAINERS | LLDAP | BOOTSTRAP | Copy static JSON files
      ansible.builtin.copy:
        src: config/lldap
        dest: /home/podman/containers/config
        owner: podman
        group: podman
        mode: "0755"
    # NOTE: writing out secrets to plain text is genuinely bad form, however if
    #       an attacker is able to read these we're already very screwed
    - name: CONTAINERS | LLDAP | BOOTSTRAP | Deploy JSON template files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: podman
        group: podman
        mode: "0640"
        force: false # do NOT overwrite secrets if they exist
      loop:
        # yamllint disable rule:line-length
        - src: config/lldap/user-configs/admin.json.j2
          dest: /home/podman/containers/config/lldap/user-configs/admin.json
        - src: config/lldap/user-configs/lldap_bind_user.json.j2
          dest: /home/podman/containers/config/lldap/user-configs/lldap_bind_user.json
        - src: config/lldap/user-configs/lldap_password_manager.json.j2
          dest: /home/podman/containers/config/lldap/user-configs/lldap_password_manager.json
        # yamllint enable rule:line-length
      notify:
        - Bootstrap LLDAP

- name: CONTAINERS | LLDAP | Install containers
  vars:
    podman_quadlet_specs:
      # list order determined by dependencies - do NOT modify
      - template_src: lldap-db.volume.j2
      - template_src: lldap-db.container.j2
      - template_src: lldap.container.j2
      - template_src: lldap-discord.container.j2
    podman_secrets:
      - name: lldap-bind-user-pass
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ lldap_bind_user_pass }}"
      - name: lldap-discord-bot-token
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ containers_lldap_discord_bot_token }}"
      - name: lldap-jwt-secret
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ lldap_jwt_secret }}"
      - name: lldap-key-seed
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ lldap_key_seed }}"
      - name: lldap-ldap-user-pass
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ lldap_ldap_user_pass }}"
      - name: lldap-password-manager-pass
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ lldap_password_manager_pass }}"
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
    name: fedora.linux_system_roles.podman

- name: CONTAINERS | LLDAP | Append database information to automated backup
  vars:
    lldap_db:
      - type: pgsql
        host: lldap-db
        name: lldap
        user: lldapuser
        pass: lldappass
  ansible.builtin.set_fact:
    containers_database_list: "{{ containers_database_list + lldap_db }}"
