###
### mapletree.moe - system configuration management
### containers - lldap - deploy lldap to target system
###
---
# TODOS: health checks
#        automated database backups
#        automatic dependency resolution
#        low priority - create local vault with secrets
- name: CONTAINERS | LLDAP | Check dependencies
  ansible.builtin.fail:
    msg: |
      !!!ERROR!!!
      !!!ERROR!!! {{ ansible.fqdn }} - roles/containers/lldap.yaml:19
      !!!ERROR!!! traefik is a hard dependency of lldap.
      !!!ERROR!!! you must add it to `containers_services_enabled` before the
      !!!ERROR!!! declaration of lldap.
      !!!ERROR!!!
  when: "'traefik' not in containers_services_enabled"

- name: CONTAINERS | LLDAP | Create database backup folder
  ansible.builtin.file:
    path: /home/podman/containers/backup/lldap-db
    state: directory
    owner: podman
    group: podman
    mode: "0755"

- name: CONTAINERS | LLDAP | Configure podman
  block:
    - name: CONTAINERS | LLDAP | PODMAN | Install containers
      vars:
        podman_fail_if_too_old: true
        podman_quadlet_specs:
          # list order determined by dependencies - do NOT modify
          - template_src: lldap-network.network.j2
          - template_src: lldap-data.volume.j2
          - template_src: lldap-db-data.volume.j2
          - template_src: lldap-db.container.j2
          - template_src: lldap.container.j2
        podman_prune_images: true
        podman_pull_image: true
        podman_run_as_user: podman
        podman_run_as_group: podman
        podman_secrets:
          - name: lldap-db-password
            state: present
            skip_existing: true # do not overwrite if secret exists
            # yamllint disable-line rule:line-length
            data: "{{ lookup('community.general.random_string', special=false, length=20) }}"
          - name: lldap-jwt-secret
            state: present
            skip_existing: true # do not overwrite if secret exists
            # yamllint disable-line rule:line-length
            data: "{{ lookup('community.general.random_string', special=false, length=20) }}"
          - name: lldap-key-seed
            state: present
            skip_existing: true # do not overwrite if secret exists
            # yamllint disable-line rule:line-length
            data: "{{ lookup('community.general.random_string', special=false, length=20) }}"
          - name: lldap-ldap-user-pass
            state: present
            skip_existing: true # do not overwrite if secret exists
            # yamllint disable-line rule:line-length
            data: "{{ lookup('community.general.random_string', special=false, length=20) }}"
        podman_validate_certs: true
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
        name: fedora.linux_system_roles.podman
    - name: CONTAINERS | LLDAP | PODMAN | Flush podman handlers
      ansible.builtin.meta: flush_handlers
