###
### mapletree.moe - system configuration management
### containers role - setup podman on target systems
###
---
- name: USERS | Configure subuid and subgid for podman user
  vars:
    subid_users: # noqa var-naming
      - podman
  ansible.builtin.include_role:
    name: subuid_subgid

- name: PODMAN | Enable podman.socket service for podman user
  vars:
    systemd_enabled_units:
      - item: podman.socket
        user: podman
    systemd_started_units:
      - item: podman.socket
        user: podman
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.systemd

- name: PODMAN | Deploy podman to target system
  vars:
    podman_fail_if_too_old: true
    podman_quadlet_specs: "{{ containers_installed_services }}"
    podman_prune_images: true
    podman_run_as_user: podman
    podman_run_as_group: podman
    podman_pull_image: true
    podman_validate_certs: true
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.podman

- name: FIREWALL | Enable port forwarding for web services
  vars:
    firewall:
      - forward_port:
          - port: 80
            proto: tcp
            to_port: 8080
          - port: 443
            proto: tcp
            to_port: 8443
          - port: 443
            proto: udp
            to_port: 8443
      - service: http
        state: enabled
      - service: https
        state: enabled
      - service: http3
        state: enabled
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.firewall
  when: containers_enable_webservices
