###
### mapletree.moe - system configuration management
### containers role - setup podman on target systems
###
---
# TODO: a podman socket proxy could be good for security?
- name: CONTAINERS | Install packages
  ansible.builtin.package:
    name:
      - container-tools
    state: present
    update_cache: true

- name: CONTAINERS | Configure subuid and subgid for podman user
  # rootless podman requires that the user and group it is set to run as to have
  # subuid and subgid ranges defined. normally this would be done by podman if
  # it was installed when the user was created, but we use this role to install
  # podman after the fact. thus, this task is required.
  # https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/building_running_and_managing_containers/assembly_starting-with-containers_building-running-and-managing-containers
  vars:
    subid_users: # noqa var-naming
      - podman
  ansible.builtin.include_role:
    # https://github.com/rwxd/ansible-role-subuid_subgid
    name: subuid_subgid

# using containers with SELinux requires additional policy options to be enabled
- name: CONTAINERS | Configure SELinux
  block:
    - name: CONTAINERS | SELINUX | Install SELinux policy modules
      vars:
        selinux_modules:
          # TODO: these two modules are actually udica templates. we should
          #       figure out how to use these templates directly on the host.
          - path: selinux/base_container.cil
            priority: 350
            state: enabled
          - path: selinux/net_container.cil
            priority: 350
            state: enabled
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_selinux/
        name: fedora.linux_system_roles.selinux
    - name: CONTAINERS | SELINUX | Flush SELinux handlers
      ansible.builtin.meta: flush_handlers

- name: CONTAINERS | Configure SystemD
  block:
    - name: CONTAINERS | SYSTEMD | Install SystemD sockets and services
      # rootless podman by default uses cni networking modules to route
      # traffic to containers. this can at times be quite slow. it is much
      # faster to use systemd-socket-activation and directly bind both the
      # port and the container to a unix socket.
      # https://www.redhat.com/en/blog/socket-activation-podman
      # https://github.com/eriksjolund/podman-traefik-socket-activation
      vars:
        # TODO: only enable the podman socket on hosts that actually need it
        systemd_enabled_units:
          - item: podman.socket
            user: podman
          - item: user-network-online.service
            user: podman
        systemd_started_units:
          - item: podman.socket
            user: podman
          - item: user-network-online.service
            user: podman
        systemd_unit_file_templates:
          - item: user-network-online.service.j2
            # https://access.redhat.com/solutions/7004860
            user: podman
            state: present
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_systemd/
        name: fedora.linux_system_roles.systemd
    - name: CONTAINERS | SYSTEMD | Flush systemd handlers
      ansible.builtin.meta: flush_handlers

- name: CONTAINERS | Install and configure enabled containers
  ansible.builtin.include_tasks:
    file: "{{ service_name }}.yaml"
  loop: "{{ containers_services_enabled }}"
  loop_control:
    loop_var: service_name
