###
### mapletree.moe - system configuration management
### containers role - setup podman on target systems
###
---
- name: COMMON | USERS | Configure subuid and subgid for podman user
  vars:
    subid_users: # noqa var-naming
      - podman
  ansible.builtin.include_role:
    name: subuid_subgid

- name: WEBSERVICES | Enable webservices on target system
  when: containers_enable_webservices
  block:
    - name: WEBSERVICES | FIREWALL | Enable port forwarding for web services
      vars:
        firewall:
          - zone: public
          - forward_port:
              - port: 80
                proto: tcp
                toport: 8080
              - port: 443
                proto: tcp
                toport: 8443
              - port: 443
                proto: udp
                toport: 8443
            state: enabled
          - service: http
            state: enabled
          - service: https
            state: enabled
          - service: http3
            state: enabled
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.firewall

    - name: WEBSERVICES | SELINUX | Enable SELinux modules for traefik container
      vars:
        selinux_modules:
          - path: base_container.cil
            state: enabled
          - path: net_container.cil
            state: enabled
          - path: traefik.cil
            state: enabled
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.selinux

    # yamllint disable-line rule:line-length
    - name: WEBSERVICES | SOCKETS | Deploy sockets required for traefik functionality
      vars:
        systemd_unit_file_templates:
          - item: http.socket.j2
            user: podman
            state: present
          - item: https.socket.j2
            user: podman
            state: present
        systemd_enabled_units:
          - item: http.socket
            user: podman
          - item: https.socket
            user: podman
          - item: podman.socket
            user: podman
        systemd_started_units:
          # we can't start the web sockets until the services are deployed
          - item: podman.socket
            user: podman
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.systemd
    - name: WEBSERVICES | CONTAINERS | Deploy traefik containers to host
      vars:
        podman_fail_if_too_old: true
        podman_quadlet_specs:
          - template_src: traefik.network.j2
          - template_src: traefik.volume.j2
          - template_src: traefik.container.j2
        podman_prune_images: true
        podman_pull_image: true
        podman_run_as_user: podman
        podman_run_as_group: podman
        podman_validate_certs: true
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.podman

- name: COMMON | SERVICES | Deploy podman containers to target system
  vars:
    podman_fail_if_too_old: true
    podman_quadlet_specs: "{{ containers_installed_services }}"
    podman_prune_images: true
    podman_pull_image: true
    podman_run_as_user: podman
    podman_run_as_group: podman
    podman_validate_certs: true
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.podman
