# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - sonarr - deploy sonarr to target system
###
---
- name: CONTAINERS | SONARR | Check dependencies
  when: "'traefik' not in containers_services_enabled"
  ansible.builtin.fail:
    # yamllint disable rule:line-length
    msg: |
      !!!ERROR!!!
      !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/tasks/sonarr.yaml:9
      !!!ERROR!!! sonarr has unsatisfied dependencies. please review.
      !!!ERROR!!!
    # yamllint enable rule:line-length

- name: CONTAINERS | SONARR | Generate secrets
  # while we generate new secrets in this step, they are NOT deployed later
  # unless they are needed
  ansible.builtin.set_fact:
    # sonarr's api key is 32 characters
    # Sonarr/src/NzbDrone.Core/Configuration/ConfigFileProvider.cs:463
    # yamllint disable-line rule:line-length
    sonarr_api_key: "{{ lookup('community.general.random_string', special=false, length=32) }}"

- name: CONTAINERS | SONARR | Install containers
  vars:
    podman_quadlet_specs:
      # list order determined by dependencies - do NOT modify
      - template_src: sonarr.volume.j2
      - template_src: sonarr-backup.volume.j2
      - template_src: sonarr.container.j2
    podman_secrets:
      - name: sonarr-api-key
        state: present
        skip_existing: true # do not overwrite if secret exists
        data: "{{ sonarr_api_key }}"
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
    name: fedora.linux_system_roles.podman
