# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - traefik - deploy traefik to target system
###
---
- name: SERVICES | TRAEFIK | Configure firewall
  block:
    - name: SERVICES | TRAEFIK | FIREWALL | Set firewall policy
      vars:
        firewall:
          - zone: public
          # forward privileged ports 80 and 443 to non-privileged 8080 and 8443
          # this prevents the need for traefik to run as root
          # https://access.redhat.com/solutions/18843
          - forward_port:
              - port: 80
                proto: tcp
                toport: 8080
              - port: 443
                proto: tcp
                toport: 8443
              - port: 443
                proto: udp
                toport: 8443
            state: enabled
          # enable the http, https, and http3 services within firewalld.
          # prefer to use services over ports to keep policy cleaner
          - service: http
            state: enabled
          - service: https
            state: enabled
          - service: http3
            state: enabled
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_firewall/
        name: fedora.linux_system_roles.firewall

    - name: SERVICES | TRAEFIK | FIREWALL | Flush firewall handlers
      ansible.builtin.meta: flush_handlers

- name: SERVICES | TRAEFIK | Configure SELinux
  # allow traefik to access `podman.socket` for dynamic configuration
  # https://kcore.org/2023/12/13/adventures-with-rootless-containers/
  block:
    - name: SERVICES | TRAEFIK | SELINUX | Install SELinux policy modules
      vars:
        selinux_modules:
          - path: selinux/traefik.cil
            state: enabled
        selinux_ports:
          - ports: 8080
            proto: tcp
            setype: http_port_t
            state: present
          - ports: 8443
            proto: tcp
            setype: http_port_t
            state: present
          - ports: 8443
            proto: udp
            setype: http_port_t
            state: present
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_selinux/
        name: fedora.linux_system_roles.selinux

    - name: SERVICES | TRAEFIK | SELINUX | Flush SELinux handlers
      ansible.builtin.meta: flush_handlers

- name: SERVICES | TRAEFIK | Configure SystemD
  block:
    - name: SERVICES | TRAEFIK | SYSTEMD | Install SystemD sockets
      # systemd-socket-activation results in faster networking than standard
      # rootless podman networks
      # https://www.redhat.com/en/blog/socket-activation-podman
      vars:
        systemd_enabled_units:
          - item: traefik-web.socket
            user: podman
          - item: traefik-websecure.socket
            user: podman
        systemd_unit_file_templates:
          - item: traefik-web.socket.j2
            user: podman
            state: present
          - item: traefik-websecure.socket.j2
            user: podman
            state: present
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_systemd/
        name: fedora.linux_system_roles.systemd

    - name: SERVICES | TRAEFIK | SYSTEMD | Flush systemd handlers
      ansible.builtin.meta: flush_handlers

- name: SERVICES | TRAEFIK | Copy configuration files
  ansible.builtin.copy:
    src: traefik
    dest: /home/podman/containers
    owner: podman
    group: podman
    mode: "0755"

- name: SERVICES | TRAEFIK | Configure podman
  block:
    - name: SERVICES | TRAEFIK | PODMAN | Install containers
      vars:
        podman_quadlet_specs:
          # list order determined by dependencies - do NOT modify
          # NOTE: the volume is needed to store the acme certificates
          - template_src: traefik.volume.j2
          - template_src: traefik.container.j2
      ansible.builtin.include_role:
        # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
        name: fedora.linux_system_roles.podman
