# code: language=ansible

###
### mapletree.moe - system configuration management
### containers - whoami - deploy lldap to target system
###
---
- name: CONTAINERS | WHOAMI | Check dependencies
  when: "'traefik' not in containers_services_enabled"
  ansible.builtin.fail:
    # yamllint disable rule:line-length
    msg: |
      !!!ERROR!!!
      !!!ERROR!!! {{ ansible_facts['fqdn'] }} - roles/containers/tasks/whoami.yaml:9
      !!!ERROR!!! whoami has unsatisfied dependencies. please review.
      !!!ERROR!!!
    # yamllint enable rule:line-length

- name: CONTAINERS | WHOAMI | Install containers
  vars:
    podman_quadlet_specs:
      - template_src: badapple.container.j2
      - template_src: whoami.container.j2
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_podman/
    name: fedora.linux_system_roles.podman
