###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: CONFIGURE | Deploy standard server configuration
  hosts: all
  become: true
  tasks:
    - name: CONFIGURE | Deploy network configuration
      ansible.builtin.include_tasks:
        file: ../tasks/config_network.yaml
    - name: Ensure system is registered with RedHat but disable Insights
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ redhat_activation_key }}"
        rhc_organization: "{{ redhat_organization }}"
        rhc_insights:
          state: absent
          remediation: absent
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
    - name: CONFIGURE | Deploy `tuned` daemon configuration
      # set profile in system's host variables
      ansible.builtin.include_role:
        name: giovtorres.tuned
    - name: CONFIGURE | Deploy user and group configuration
      ansible.builtin.include_tasks:
        file: ../tasks/config_users.yaml
    - name: CONFIGURE | Deploy Postfix as a null-relay to forward mail
      ansible.builtin.include_tasks:
        file: ../tasks/config_postfix.yaml
    - name: CONFIGURE | Configure package manager and install tools
      ansible.builtin.include_tasks:
        file: ../tasks/config_packages.yaml
