###
### mapletree.moe - system configuration management
### update containers configuration
###
---
- name: CONTAINERS | Deploy container configuration
  hosts: all
  become: true
  tasks:
    - name: CONTAINERS | Activate container configuration
      ansible.builtin.include_role:
        name: containers
