# code: language=ansible

###
### mapletree.moe - system configuration management
### perform compliance configuration for server
###
---
- name: HARDENING | Run hardening role to apply compliance policy
  hosts: all
  become: true
  tasks:
    - name: HARDENING | Include hardening role
      ansible.builtin.include_role:
        name: hardening
