###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: Deploy server configuration
  hosts: all
  become: true
  tasks:
    - name: Ensure bootloader password is set
      # NOTE: password is set in group_vars
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.bootloader
    - name: Ensure system networking is properly configured
      ansible.builtin.include_tasks:
        file: ../tasks/configure_network.yaml
    - name: Ensure system is registered with RedHat but disable Insights
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ redhat_activation_key }}"
        rhc_organization: "{{ redhat_organization }}"
        rhc_insights:
          state: absent
          remediation: absent
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
    - name: Ensure system is using proper tuned profile
      # set profile in system's host variables
      ansible.builtin.include_role:
        name: giovtorres.tuned
    - name: Ensure user configuration matches policy
      ansible.builtin.include_tasks:
        file: ../tasks/configure_users.yaml
    - name: Ensure Postfix is configured to act as a mail relay
      ansible.builtin.include_tasks:
        file: ../tasks/postfix_null_relay.yaml
    - name: Ensure Automatic Updates are enabled on host
      ansible.builtin.include_tasks:
        file: ../tasks/automatic_updates.yaml
    - name: Ensure CIS Server Level 2 Benchmark Compliance
      ansible.builtin.include_tasks:
        file: ../tasks/compliance_configuration.yaml

#   roles:
#     - role: create_users
#       become: true
#     - role: general_config
#       become: true
