###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: Deploy server configuration
  hosts: all
  become: true
  tasks:
    - name: Ensure system is registered with RedHat but disable Insights
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ redhat_activation_key }}"
        rhc_organization: "{{ redhat_organization }}"
        rhc_insights:
          state: absent
          remediation: absent
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
    - name: Ensure system is using proper tuned profile
      # set profile in system's host variables
      ansible.builtin.include_role:
        name: giovtorres.tuned
    - name: Ensure Postfix is configured to act as a mail relay
      ansible.builtin.include_role:
        name: postfix_relay

#   roles:
#     - role: create_users
#       become: true
#     - role: general_config
#       become: true
