# code: language=ansible

###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: COMMON | Deploy standard server configuration
  hosts: all
  become: true
  tasks:
    - name: COMMON | Deploy COMMON server configuration role
      ansible.builtin.include_role:
        name: common
