###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: CONFIGURE | Deploy standard server configuration
  hosts: all
  become: true
  tasks:
    - name: CONFIGURE | Deploy COMMON server configuration role
      ansible.builtin.include_role:
        name: common
    - name: CONFIGURE | Install ZFS and load module on boot
      ansible.builtin.include_tasks:
        file: ../tasks/config_zfs.yaml
      when: ansible_architecture == "x86_64"
    - name: CONFIGURE | Install NVIDIA and load module on boot
      ansible.builtin.include_tasks:
        file: ../tasks/config_nvidia.yaml
      when: ansible_architecture == "x86_64"
