###
### mapletree.moe - system configuration management
### update system configuration
###
---
- name: Deploy server configuration
  hosts: all
  become: true
  tasks:
    - name: Ensure system is registered with RHEL but disable insights
      vars:
        rhc_auth:
          activation_keys:
            keys:
              - "{{ redhat_activation_key }}"
        rhc_organization: "{{ redhat_organization }}"
        rhc_insights:
          state: absent
          remediation: absent
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.rhc
    - name: Ensure system is using proper tuned profile
      # set profile in host variables
      ansible.builtin.include_role:
        name: giovtorres.tuned
    - name: Ensure Postfix Null Relay is correctly set up
      vars:
        postfix_conf:
          inet_interfaces: "loopback-only"
          mydestination: ""
          relayhost: "{{ postfix_relayhost }}"
          sender_canonical_classes: "envelope_sender, header_sender"
          sender_canonical_maps: "regexp:/etc/postfix/sender_canonical_maps"
          smtp_header_checks: "regexp:/etc/postfix/smtp_header_checks"
          smtp_sasl_auth_enable: "yes"
          smtp_sasl_password_maps: "hash:/etc/postfix/sasl_passwd"
          smtp_sasl_security_options: "noanonymous"
          smtp_sasl_tls_security_options: "noanonymous"
          smtp_tls_policy_maps: "hash:/etc/postfix/tls_policy"
          smtpd_client_restrictions: "permit_mynetworks,reject"
          smtp_use_tls: "yes"
        postfix_files:
          - name: sender_canonical_maps
            content: "{{ postfix_sender_canonical_maps }}"
          - name: smtp_header_checks
            content: "{{ postfix_smtp_header_checks }}"
          - name: sasl_passwd
            content: "{{ postfix_sasl_passwd }}"
            postmap: true
          - name: tls_policy
            content: "{{ postfix_tls_policy }}"
            postmap: true
      block:
        - name: Ensure cyrus-sasl-plain is present on system
          ansible.builtin.package:
            name: cyrus-sasl-plain # smtp2go requirement
            state: present
        - name: Install and configure Postfix
          ansible.builtin.include_role:
            name: fedora.linux_system_roles.postfix
          no_log: false


#   roles:
#     - role: postfix_relay
#       become: true
#     - role: create_users
#       become: true
#     - role: general_config
#       become: true
