###
### mapletree.moe - system configuration management
### provision new cloud servers
###
---
# TODO: this could likely be made into a task
- name: Provision Unconfigured Cloud Servers
  hosts: all
  become: true
  tasks:
    - name: PROVISION | Upgrade target systems to latest
      ansible.builtin.include_tasks:
        file: ../tasks/provision/update.yaml
      when: ansible_distribution != "RedHat"
    - name: PROVISION | Deploy `infra.convert2rhel`
      ansible.builtin.include_tasks:
        file: ../tasks/provision/convert.yaml
      when: ansible_distribution != "RedHat"
    - name: PROVISION | Run post-conversion cleanup on target systems
      ansible.builtin.include_tasks:
        file: ../tasks/provision/post.yaml
      when: ansible_distribution != "RedHat"
