###
### mapletree.moe - system configuration management
### provision new cloud servers
###
---
# TODO: this could likely be made into a task
- name: Provision Unconfigured Cloud Servers
  hosts: all
  become: true
  tasks:
    - name: Ensure packages on conversions target have been updated to latest
      ansible.builtin.include_tasks:
        file: ../tasks/provision_update.yaml
      when: ansible_distribution != "RedHat"
    - name: Perform analysis and conversion of target systems to genuine RHEL
      ansible.builtin.include_tasks:
        file: ../tasks/provision_convert.yaml
      when: ansible_distribution != "RedHat"
    - name: Run post-conversion cleanup on target systems
      ansible.builtin.include_tasks:
        file: ../tasks/provision_post.yaml
      when: ansible_distribution != "RedHat"
