###
### mapletree.moe - system configuration management
### perform compliance configuration for server
###
---
- name: Ensure system is compliant with CIS Server Level 2 Benchmark
  hosts: all
  become: true
  tasks:
    - name: COMPLIANCE | BENCHMARK | Run ansible-lockdown CIS benchmark
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/benchmark.yaml
    - name: COMPLIANCE | Configure bootloader
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/bootloader.yaml
    - name: COMPLIANCE | Configure chrony and system timekeeping
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/timesync.yaml
    - name: COMPLIANCE | Configure firewall
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/firewalld.yaml
    - name: COMPLIANCE | Configure kernel and kernel modules
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/kernel.yaml
    - name: COMPLIANCE | Configure package manager and packages
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/packages.yaml
    - name: COMPLIANCE | Configure system services and features
      ansible.builtin.include_tasks:
        file: ../tasks/compliance/system.yaml
    # FIXME: use a handler
    - name: COMPLIANCE | Reboot the server to apply compliance
      ansible.builtin.reboot:
        reboot_timeout: 600
