###
### mapletree.moe - system configuration management
### containers role - default variable configuration
###
---
containers_enable_webservices: true
containers_traefik_dashboard_password: changeme
containers_installed_services:
  - template_src: whoami.container.j2
