# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - configure system settings common to all devices
###
---
# the cloud we use does not natively provide RHEL images, so we use terraform to
# install a RHEL clone and then convert the clone to genuine RHEL. this is not
# technically supported by redhat.
- name: COMMON | Convert RHEL Clones to genuine RHEL
  when:
    - common_convert_enabled
    - ansible_facts['distribution'] != "RedHat"
  ansible.builtin.include_tasks:
    file: convert.yaml

# disable cloud-init after first boot configuration
# https://cloudinit.readthedocs.io/en/stable/howto/disable_cloud_init.html
- name: COMMON | CLOUD-INIT | Create file disabling cloud-init
  ansible.builtin.file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    owner: root
    group: root
    mode: "0644"

- name: COMMON | Configure system network
  ansible.builtin.include_tasks:
    file: network.yaml

- name: COMMON | PACKAGES | Configure packages and updates
  ansible.builtin.include_tasks:
    file: packages.yaml

- name: COMMON | Install nvidia compute driver and container utilities
  when: common_nvidia_enabled
  ansible.builtin.include_tasks:
    file: nvidia.yaml

- name: COMMON | Enable Postfix acting as a null-relay on target host
  when: common_postfix_enabled
  ansible.builtin.include_tasks:
    file: postfix.yaml

- name: COMMON | REDHAT | Configure RedHat services
  when: common_redhat_enabled
  ansible.builtin.include_tasks:
    file: redhat.yaml

- name: COMMON | TUNED | Configure system tuning based on system type
  ansible.builtin.include_tasks:
    file: tuned.yaml

- name: COMMON | USERS | Configure standard users & groups for target system
  ansible.builtin.include_tasks:
    file: users.yaml

- name: COMMON | Install ZFS kernel module and tools
  when: common_zfs_enabled
  ansible.builtin.include_tasks:
    file: zfs.yaml
