# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - configure system settings common to all devices
###
---
# TODOs: Sudo configuration

# disable cloud-init after first boot configuration
# https://cloudinit.readthedocs.io/en/stable/howto/disable_cloud_init.html
- name: COMMON | Disable cloud-init if needed
  block:
    - name: COMMON | CLOUD-INIT | Check if cloud-init is in use
      ansible.builtin.stat:
        path: /etc/cloud
      register: cloud_init_dir
    - name: COMMON | CLOUD-INIT | Check if disabled file exists
      ansible.builtin.stat:
        path: /etc/cloud/cloud-init.disabled
      register: cloud_init_file
      when: cloud_init_dir.stat.exists
    - name: COMMON | CLOUD-INIT | Disable cloud-init
      ansible.builtin.file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
        owner: root
        group: root
        mode: "0644"
      when:
        - cloud_init_dir.stat.exists
        - not cloud_init_file.stat.exists

- name: COMMON | Configure system network
  ansible.builtin.include_tasks:
    file: network.yaml

- name: COMMON | PACKAGES | Configure packages and updates
  ansible.builtin.include_tasks:
    file: packages.yaml

- name: COMMON | Install nvidia compute driver and container utilities
  when: common_nvidia_enabled
  ansible.builtin.include_tasks:
    file: nvidia.yaml

- name: COMMON | Enable Postfix acting as a null-relay on target host
  when: common_postfix_enabled
  ansible.builtin.include_tasks:
    file: postfix.yaml

- name: COMMON | TUNED | Configure system tuning based on system type
  ansible.builtin.include_tasks:
    file: tuned.yaml

- name: COMMON | USERS | Configure standard users & groups for target system
  ansible.builtin.include_tasks:
    file: users.yaml

- name: COMMON | Install ZFS kernel module and tools
  when: common_zfs_enabled
  ansible.builtin.include_tasks:
    file: zfs.yaml
