# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - network - configure system networking
###
---
- name: COMMON | NETWORK | Set system hostname from inventory file
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    # RHEL/EL/CentOS 7+ use 'systemd' over 'redhat'
    use: systemd

- name: COMMON | NETWORK | Configure hosts file
  block:
    # yamllint disable rule:line-length
    - name: COMMON | NETWORK | HOSTS | Set ipv4 localhosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"
        regex: "127.0.0.1"
    - name: COMMON | NETWORK | HOSTS | Set ipv6 localhosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "::1 {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"
        regex: "::1"
    - name: COMMON | NETWORK | HOSTS | Set ansible hosts in file
      ansible.builtin.lineinfile:
        path: hosts
        line: "{{ hostvars[item].ansible_all_ipv4_addresses.0 }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
        regexp: "{{ hostvars[item].ansible_fqdn }}"
      loop: "{{ groups['servers'] }}"
    # yamllint enable rule:line-length

# TODO: this sometimes seizes up in the CI/CD pipeline, why?
- name: COMMON | NETWORK | NM | Configure DHCP and static DNS Servers
  vars:
    network_provider: nm
    network_state:
      interfaces:
        - name: "{{ ansible_facts['default_ipv4']['interface'] }}"
          type: ethernet
          state: up
          ipv4:
            enabled: true
            auto-dns: false
            auto-gateway: true
            auto-routes: true
            dhcp: true
          ipv6:
            enabled: false # IPV6: enable ipv6 then modify "IPV6" comments
            auto-dns: false
            auto-gateway: false
            auto-routes: false
            autoconf: false
            dhcp: false
      dns-resolver:
        config:
          server:
            - 1.1.1.1
            - 1.0.0.1
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_network/
    name: fedora.linux_system_roles.network

- name: COMMON | NETWORK | NM | Flush network handlers
  ansible.builtin.meta: flush_handlers

# IPV6: this is an ugly hack because we don't have ipv6
# without this hack postfix will fail to start, causing the postfix role to
# fail since it first starts the service to check for a successful install
- name: COMMON | NETWORK | HOSTS | Remove ipv6 localhost from /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "::1"
    state: absent
