# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - network - configure system networking
###
---
# TODO: this sometimes seizes up in the CI/CD pipeline, why?
- name: COMMON | NETWORK | NM | Configure DHCP and static DNS Servers
  vars:
    network_provider: nm
    network_state:
      interfaces:
        - name: "{{ ansible_facts['default_ipv4']['interface'] }}"
          type: ethernet
          state: up
          ipv4:
            enabled: true
            auto-dns: false
            auto-gateway: true
            auto-routes: true
            dhcp: true
          ipv6:
            enabled: false # TODO: enable ipv6 then modify "IPV6" comments
            auto-dns: false
            auto-gateway: false
            auto-routes: false
            autoconf: false
            dhcp: false
      dns-resolver:
        config:
          server:
            - 1.1.1.1
            - 1.0.0.1
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_network/
    name: fedora.linux_system_roles.network

- name: COMMON | NETWORK | NM | Flush network handlers
  ansible.builtin.meta: flush_handlers

# IPV6: this is an ugly hack because we don't have ipv6
# without this hack postfix will fail to start, causing the postfix role to
# fail since it first starts the service to check for a successful install
- name: COMMON | NETWORK | HOSTS | Remove ipv6 localhost from /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ^::1
    state: absent
