# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - nvidia - install nvidia drivers and tools
###
---
# https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/index.html#red-hat-enterprise-linux
# install gpg key to avoid interactive prompt on package install
- name: NVIDIA | Install NVIDIA software repository public key
  ansible.builtin.rpm_key:
    # yamllint disable-line rule:line-length
    key: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub
    fingerprint: 610C 7B14 E068 A878 070D A4E9 9CD0 A493 D42D 0685
    state: present

- name: NVIDIA | Install NVIDIA dnf software repository
  ansible.builtin.yum_repository:
    name: cuda-rhel9-x86_64
    # UPGRADE: change this on upgrade
    # yamllint disable-line rule:line-length
    baseurl: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64
    description: nvidia-driver repository
    enabled: true
    gpgcheck: true
    # yamllint disable-line rule:line-length
    gpgkey: https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/D42D0685.pub
    mode: "0644"

# TODO: if nvidia decides we deserve a 570 precompiled kmod, update this
- name: NVIDIA | Set nvidia driver to 565 branch to access precompiled kmod
  ansible.builtin.dnf:
    name: "@nvidia-driver:565"
    state: present

- name: NVIDIA | Install NVIDIA drivers and container-tools
  ansible.builtin.dnf:
    # TODO: when 570 kABI package is available explicitly include it
    name:
      - nvidia-driver-cuda
      - nvidia-container-toolkit
    state: present

# NOTE: enabling the driver won't cause any problems even if the system
#       doesn't have one, the driver will simply fail to load and print an error
- name: NVIDIA | Enable nvidia driver on reboot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/nvidia.conf
    content: "nvidia"
    owner: root
    group: root
    mode: "0644"
