# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - redhat - configure subscription and insights
###
---
# conversion script still uses individual account authentication, this converts
# the rhel license to the organizational license and enables insights
- name: COMMON | REDHAT | Authenticate system with Redhat, Enable Insights
  vars:
    rhc_auth:
      activation_keys:
        keys:
          - "{{ common_redhat_key }}"
    rhc_organization: "{{ common_redhat_org }}"
    rhc_insights:
      state: present
      remediation: absent
  ansible.builtin.include_role:
    # https://galaxy.ansible.com/ui/repo/published/fedora/linux_system_roles/docs/README_rhc/
    name: fedora.linux_system_roles.rhc

- name: COMMON | REDHAT | Flush redhat handlers
  ansible.builtin.meta: flush_handlers
