# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - tuned - configure system tuning
###
---
# NOTE: DISA STIG explicitly provides a rule for turning the tuned daemon OFF,
#       however the potential performance benefits outweigh the security risks
- name: COMMON | TUNED | Set tuned to 'virtual-guest' on virtual systems
  when: ansible_facts['virtualization_role'] == "guest"
  vars:
    tuned_active_builtin_profile: "virtual-guest"
  ansible.builtin.include_role:
    # https://github.com/giovtorres/ansible-role-tuned
    name: giovtorres.tuned

- name: COMMON | TUNED | Set tuned to 'throughput-performance' on bare metal
  when: ansible_facts['virtualization_role'] != "guest"
  vars:
    tuned_active_builtin_profile: "virtual-guest"
  ansible.builtin.include_role:
    # https://github.com/giovtorres/ansible-role-tuned
    name: giovtorres.tuned

- name: TUNED | Flush tuned handlers
  ansible.builtin.meta: flush_handlers
