# code: language=ansible

###
### mapletree.moe - system configuration management
### common role - users & groups - configure standard users and groups
###
---
- name: GROUPS | GROUPS | Ensure group 'mapletree' - GID '1001' exists
  ansible.builtin.group:
    name: mapletree
    gid: 1001
    state: present

- name: COMMON | GROUPS | Ensure group 'podman' - GID '1000' exists
  ansible.builtin.group:
    name: podman
    gid: 1000
    state: present

# TODO: Eventually we should actually roll out version controlled passwords
#       for mapletree, root, and podman, and transition to using become with the
#       vaulted password.
- name: COMMON | USERS | Ensure user "mapletree" - UID '1001' - locked exists
  ansible.builtin.user:
    name: mapletree
    comment: Mapletree.moe Administrator
    uid: 1001
    group: mapletree
    password_lock: true
    groups: mapletree,users,wheel
    state: present

- name: COMMON | USERS | Ensure user "podman" - UID '1000' - locked exists
  ansible.builtin.user:
    name: podman
    comment: Mapletree.moe Container User
    uid: 1000
    group: podman
    password_lock: true
    groups: podman,users
    state: present

- name: COMMON | USERS | Ensure user "root" is locked to prevent login
  ansible.builtin.user:
    name: root
    password_lock: true

- name: COMMON | USERS | MAPLETREE | Set up ssh authorized_keys
  ansible.posix.authorized_key:
    user: mapletree
    state: present
    key: '{{ item }}'
  loop: "{{ common_mapletree_authorized_keys }}"
