###
### mapletree.moe - system configuration management
### general_config - role tasks
###
---
# NOTE: this file should contain things that will apply to ALL hosts.

#
# podman
#
- name: Ensure Podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure container-selinux is installed
  ansible.builtin.package:
    name: container-selinux
    state: present
