###
### mapletree.moe - system configuration management
### provision new cloud servers
###
---
- name: Run standardized server configuration.
  hosts: all
  roles:
    - role: update_system
      become: true
      # only do an unchecked update when preparing for convert2rhel
      when: ansible_distribution != "RedHat"
    - role: infra.convert2rhel.analysis
      become: true
      when: ansible_distribution != "RedHat"
    - role: infra.convert2rhel.convert
      become: true
      when: ansible_distribution != "RedHat"
    - role: post_conversion
      become: true
      when: ansible_distribution != "RedHat"
    - role: linux-system-roles.rhc
      become: true
