###
### mapletree.moe - Automation
### Run compliance playbook on github actions
###
---
name: Run ansible cloud provisioning playbook

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'play/provision-cloud.yaml'
      - 'tasks/provision_*.yaml'

env:
  HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Ansible
        shell: bash
        run: python -m pip install ansible
      - name: Run Ansible Playbook - provision-cloud.yaml
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: plays/provision-cloud.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yaml
