###
### mapletree.moe - Automation
### Run all playbooks on github actions
###
---
name: Deploy all playbooks

# yamllint disable-line rule:truthy
on:
  workflow_dispatch: # this playbook takes a WHILE so make it manual only

env:
  ANSIBLE_HOST_KEY_CHECKING: false  # needed for automation
  HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'
      - name: Install Ansible & Dependencies
        shell: bash
        run: pip install -r requirements.txt
      - name: Run Ansible Playbook - site.yaml
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: site.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yaml
