# code: language=yaml

###
### mapletree.moe - Automation
### Run containers playbook on github actions
###
---
  name: Deploy containers playbook

  # yamllint disable-line rule:truthy
  on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - 'play/deploy-containers.yaml'
        - 'roles/containers/**'

  env:
    ANSIBLE_HOST_KEY_CHECKING: false  # needed for automation
    HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12.9'
        - name: Install Ansible & Dependencies
          shell: bash
          run: pip install -r requirements.txt
        - name: Run Ansible Playbook - deploy-containers.yaml
          uses: dawidd6/action-ansible-playbook@v3
          with:
            playbook: plays/deploy-containers.yaml
            key: ${{secrets.SSH_PRIVATE_KEY}}
            vault_password: ${{secrets.VAULT_PASSWORD}}
            requirements: requirements.yaml
