# code: language=yaml

###
### mapletree.moe - Automation
### Run containers playbook on github actions
###
---
name: Deploy containers playbook

 # yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'play/deploy-containers.yaml'
      - 'roles/containers/**'

env:
  ANSIBLE_HOST_KEY_CHECKING: false  # needed for automation

jobs:
  create-runner:
    name: Create Hetzner Cloud runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
    steps:
      - name: Create runner
        id: create-hcloud-runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: create
          github_token: ${{ secrets.NAGATO_GITHUB_RUNNERS }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          enable_ipv6: false
          server_type: cx22
          ssh_key: 27836571
          image: rocky-9
  deploy:
    name: Deploy containers role to all servers
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Ansible & Dependencies
        shell: bash
        run: pip install -r requirements.txt
      - name: Run Ansible Playbook - deploy-containers.yaml
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: plays/deploy-containers.yaml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yaml
  delete-runner:
    name: Delete Hetzner Cloud runner
    needs:
      - create-runner # required to get output from the create-runner job
      - deploy # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Delete runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: delete
          github_token: ${{ secrets.NAGATO_GITHUB_RUNNERS }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          name: ${{ needs.create-runner.outputs.label }}
          server_id: ${{ needs.create-runner.outputs.server_id }}
